# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end


  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install language-pack-en
    # Python Pip Fabric ...
    sudo apt-get install -y python-pip python-dev build-essential
    sudo apt-get install -y build-essential libssl-dev libffi-dev python-dev
    sudo apt-get install -y libxslt-dev libxml2-dev
    sudo apt-get install -y mkisofs
    sudo apt-get install -y git
    sudo pip install virtualenv
    sudo pip install fabric
    sudo pip install jinja2
  SHELL

end
